title: Dan McDonough
description: Portfolio of Analytical and Data Science Work
show_downloads: false

author: Dan McDonough

theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache

permalink: /:title/

minima:
  skin: classic
  social_links:
    github: "DMcDonough26"
    linkedin: "dan-mcdonough-7b050810"
  hide_site_feed_link: True

nav_pages:
  - index.md
  - about.md
