title: Dan McDonough
description: Portfolio of Analytical and Data Science Work
show_downloads: false

author: Dan McDonough

theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache

permalink: /:title/

github_username: DMcDonough26
linkedin_username: dan-mcdonough-7b050810

minima:
  skin: classic
  hide_site_feed_link: true

header_pages:
  - index.md
  - about.md
