title: Dan McDonough
description: Portfolio of Analytical and Data Science Work
show_downloads: false

author:
  name: Dan McDonough

remote_theme: jekyll/minima
plugins:
  - jekyll-seo-tag

permalink: /:title/

minima:
  skin: classic
  include_css:
    - /assets/css/custom.css
  social_links:
    - title: DMcDonough26 at GitHub
      icon: github
      url: "https://github.com/dmcdonough26"
    - title: Dan McDonough at LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/dan-mcdonough-7b050810/"
  hide_site_feed_link: True
  nav_pages:
    - index.md
    - about.md


